### ISSUE TITLE
Blacklist for certain email-addresses like @gmx.de, @gmx.net, @t-online.de, @web.de

### ISSUE THREAD

**Issue by jscholtysik** [ContaoBayern/contao-ertl-bundle#4]
As already discussed, a blacklist is still needed that blocks certain email addresses for token generation. These are e.g. email addresses of:

- @gmx.de / @gmx.net
- @t-online.de
- @web.de

The list should also be expandable and should already take effect when the email address is entered in the email field, before the form can be submitted.

Joachim

**Comment by fiedsch** [comment]
The list currently hard coded [here](https://github.com/ContaoBayern/contao-ertl-bundle/blob/f2a0f2f3a3ba8535b40237f4f9ea0a6290d91f52/src/EventListener/ValidateFormFieldListener.php#L12). This is obviously not the solution we intend for production.

I wonder if we should have this via `parameters.yml`, which would be the easiest way. Or should we make this a backend module so users could add (or delete) domains.

What do you think?

**Comment by jscholtysik** [comment]
IMHO a Backend Module would be the better solution so that the client can add new entries or change existing entries more comfortable.
